service: better-dynamodb-scaling

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricAlarm"
      Resource: "*"

functions:
  change_cw_alarms:
    handler: functions/change_cw_alarm.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.monitoring
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - monitoring.amazonaws.com
              eventName:
                - PutMetricAlarm